vim.keymap.set('n', '<Leader>z', ':tabnew %<CR>', { noremap = true, silent = true })
vim.keymap.set('n', 'R', ':source $MYVIMRC<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-t>', '<C-w>l', { noremap = true, silent = true })
vim.keymap.set('n', '<C-y>', '<C-w>h', { noremap = true, silent = true })
vim.keymap.set('n', '<C-l>', '<C-w>l', { noremap = true, silent = true })
vim.keymap.set('n', '<C-h>', '<C-w>h', { noremap = true, silent = true })
