name: project
root: ~/code/<%= @settings["workspace"] %>
windows:
  - editor:
      layout: main-horizontal
      panes:
        - nvim
        - terminal_1:
        - terminal_2:
        - terminal_3:

